name: 'Automatic build'
on:
  push:
    branches:
      - main
    paths-ignore:
      - .gitignore
      - README.md
      - LICENSE

jobs:
  continuous-delivery:

    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0  # for posts's lastmod

      - name: Setup Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: '3.0'
          bundler-cache: true

      - uses: actions/checkout@master #docker://pandoc/core:2.17
      - uses: nikeee/setup-pandoc@v1
        with:
          pandoc-version: '2.17' # The pandoc version to download (if necessary) and use.
          args: "--help" # gets appended to pandoc command
      - run: echo "# Test" | pandoc -t html

      - name: Deploy
        run: bash tools/deploy.sh
